### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by saltyshiomix** [sindresorhus/ky-universal#28]
In Node.js v14, I got this error.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/salty/Documents/src/youtu-bu/node_modules/ky-universal/index.js
require() of ES modules is not supported.
require() of /Users/salty/Documents/src/youtu-bu/node_modules/ky-universal/index.js from /Users/salty/Documents/src/youtu-bu/packages/youtu-bu-sakagura/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/salty/Documents/src/youtu-bu/node_modules/ky-universal/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/salty/Documents/src/youtu-bu/node_modules/ky-universal/package.json.
```

Could you tell me why do you use `"type": "module"` in package.json?

**Comment by saltyshiomix** [comment]
Or, we should replace all `require()` to `import()`?

**Comment by sindresorhus** [comment]
I think you could have easily Googled the error and figured this out yourself.

It's also explained in the release notes: https://github.com/sindresorhus/ky-universal/releases/tag/v0.9.0

**Comment by sholladay** [comment]
@saltyshiomix Ky uses modern JavaScript features, including [ES modules](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/). We have `"type": "module"` in package.json to let Node.js and the rest of the ecosystem know that this is the case. To import Ky, you need to `import ky from 'ky'` instead of `const ky = require('ky')` or whatever older syntax you may have been using previously. You should update your other imports to use `import` as well. It should work for older dependencies, too.

If this doesn't work for some reason, it would be good to have more details to understand what is going on.

If for some reason you continue to struggle with `import`, then I would recommend using an older version of Ky, such as 0.25.1 or below. Or if you're using `ky-universal`, then 0.8.2 or below. Those versions have a UMD build for older environments. But you should use it only as a last resort.

**Comment by matveychuk** [comment]
I use import statement in my code
```
import ky from "ky-universal";

export default function Home() {
  const fetchData = async () => {
    const res = await ky
      .get("https://jsonplaceholder.typicode.com/todos/1")
      .json();
    setData(res);
    console.log(res);
  };
```
But the error is related to source code from node-modules
![image](https://user-images.githubusercontent.com/23308963/104837769-5b60cb00-58bf-11eb-90de-6cd967694de5.png)

How I can solve this issue without forking and fixing 'ky' library?

**Comment by matveychuk** [comment]
Solved this issue by downgrading ky to:
    "ky": "0.24.0",
    "ky-universal": "0.8.2"
But I think maintainers should draw attention to this issue

**Comment by wildan2711** [comment]
I'm also getting this issue, I don't know why.. I've already updated my imports to `import ky from 'ky-universal'`, and updated `ky` to version 0.26.0

```
  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/.pnpm/ky-universal@0.9.1_ky@0.26.0/node_modules/ky-universal/index.js
  at new NodeError (node:internal/errors:259:15)
  at Module._extensions..js (node:internal/modules/cjs/loader:1100:13)
  at Object.require.extensions.<computed> (node_modules/.pnpm/ts-node@9.1.1_typescript@4.1.3/node_modules/ts-node/src/index.ts:1045:43)
```

**Comment by sholladay** [comment]
Hi everyone. I think what's happening to most of you is that you're using a tool like Next.js which itself uses Webpack to compile your code and that system is converting your `import` statements to `require()` calls, which are incompatible with Ky.

Please, if you're using any system like that, be sure to ask them if they have a way to keep your `import` statements intact.

**Comment by oncet** [comment]
It's definitely what @sholladay mentions. But for a moment I was completely sure that it was working fine, until it stopped working.

I wonder what's the proper way for using ky in Next.js.

**Comment by sholladay** [comment]
That's an interesting workaround! If your tooling is converting static import statements but _not_ dynamic imports, then try doing it with top-level await. Shouldn't be too ugly. Like this...

```js
const ky = await import('ky');
```

As long as the compiled code is interpreted as ESM when it is executed, that should work just fine. Top-level await is supported in most ESM environments these days.

**Comment by oncet** [comment]
It works but it's not elegant, you would need to store it in a ref or a state to share it across different callbacks in the same React component. Or import it inside each one.

Btw, I think you need to get the default export:

```
const ky = (await import("ky")).default;
```

**Comment by oncet** [comment]
It works but it's not elegant, you would need to store it in a ref or a state to share it across different callbacks in the same React component. Or import it inside each one.

Importing it at top level doesn't work:

> Module parse failed: Cannot use keyword 'await' outside an async function

Btw, I think you need to get the default export:

```javascript
const ky = (await import("ky")).default;
````

**Comment by sholladay** [comment]
You're right about needing to use `.default`, I always forget that dynamic import works like that.

And yeah, now that I think about it, while top-level `await` _does_ work in Node.js and most browsers, your component may not be executing at the top level. Your bundler might be wrapping it in an IIFE or a CommonJS module at build time, which would cause `await` to throw an error. That's rather unfortunate and honestly the best solution would be to use a bundler like [Rollup](https://rollupjs.org) that outputs an ES module by default, and then you don't even need to use dynamic import, everything will "just work". There are probably plugins or settings for Webpack to do the same thing. Then all you need to do is ensure you are executing in an ESM context at runtime, which means `<script type="module">` in the browser where you load your app.

**Comment by oncet** [comment]
Got it working using `[next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules)`.

**Comment by rohmanhm** [comment]
@oncet Can you share your config in here please?

**Comment by oncet** [comment]
> @oncet Can you share your config in here please?

Sure.

```
// next.config.js
const withTM = require("next-transpile-modules")(["ky"]);

module.exports = withTM();
```

**Comment by jc-camosun** [comment]
I still get a `Cannot use keyword 'await' outside an async function` error using this configuration and Node 14
> 
> > @oncet Can you share your config in here please?
> 
> Sure.
> 
> ```
> // next.config.js
> const withTM = require("next-transpile-modules")(["ky"]);
> 
> module.exports = withTM();
> ```

**Comment by jc-camosun** [comment]
> Btw, I think you need to get the default export:
> 
> ```js
> const ky = (await import("ky")).default;
> ```
shouldn't it be:

```js
const ky = (await import("ky-universal")).default;
```

**Comment by sholladay** [comment]
@jc-camosun what's your exact Node version?

**Comment by oncet** [comment]
> > Btw, I think you need to get the default export:
> > ```js
> > const ky = (await import("ky")).default;
> > ```
> 
> shouldn't it be:
> 
> ```js
> const ky = (await import("ky-universal")).default;
> ```

I'm using `kay`.

**Comment by RXminuS** [comment]
This has pretty much made it unusable with Next.js, if anyone figured out a good workaround can you share here and I'll make a PR in the docs.

**And all due respect for maintaining a large library like this but that was a pretty shitty response @sindresorhus**

**Comment by sindresorhus** [comment]
@RXminuS I can understand the situation is annoying. Yes, I could have been more helpful in the issue comment, but I get many issues like this every day where the poster did zero effort in Googling or debugging stuff themselves. It's both time consuming and demotivating. `ky-universal` is a 100% valid ESM package. The fact that Next.js cannot handle ESM is not really something I can control or something I should be obliged to answer support questions about. ESM has been in development for 10 years. We all knew it was coming. Webpack and Next.js could have better prepared for this. In the end, you are the one that chose to use Next.js, with all the hidden complexity that entails.

That being said, I'm happy to document workarounds for Next.js in https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c (comment on that gist with any working workarounds)

**Comment by justin-echternach** [comment]
Try adding "allowSyntheticDefaultImports": true, to tsconfig.json

**Comment by DevelopedByDavid** [comment]
> @RXminuS I can understand the situation is annoying. Yes, I could have been more helpful in the issue comment, but I get many issues like this every day where the poster did zero effort in Googling or debugging stuff themselves. It's both time consuming and demotivating. `ky-universal` is a 100% valid ESM package. The fact that Next.js cannot handle ESM is not really something I can control or something I should be obliged to answer support questions about. ESM has been in development for 10 years. We all knew it was coming. Webpack and Next.js could have better prepared for this. In the end, you are the one that chose to use Next.js, with all the hidden complexity that entails.
> 
> That being said, I'm happy to document workarounds for Next.js in https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c (comment on that gist with any working workarounds)

Some of us are not familiar with the inner workings of these massive libraries. I am using Laravel to gain a better understanding of the framework. Frameworks are designed to make things faster and easier. I was following along with a tutorial and making a project with what I am learning. Then I attempt to do what make:auth used to do and it ruined my project. now I am on attempt four. This time in accordance with Laravel docs I tried to install laravel/breeze. Now this project is ruined also as previously working views are now throwing 404. Makes no sense to me. I read a bunch of the comments on this issue and even that isn't a solution for someone like me because all of them require me to understand node or other technologies that I didn't 'choose' to use. Laravel used to work fine for me when I first learned but now it seems broken. Youre not obligated to fix the issues you find beneath your time and consideration. Your asshole attitude is the issue. Lucky for you you have a solid understanding of these issues. For the beginners, you 'demotivate' them to continue to learn. You clearly have a wealth of knowledge. Wouldn't it be nice to have a good mentor to guide us along to get where you are. Since you get the issue daily and seemingly have the time to spew shit at others, why dont you create the step by step to fix the issue and post it instead. He did google it, just like I did. Guess where Google brought me for an answer? To your condescending reply that offers no real insight. It isnt because you waste time each day or you would just post the link to guide them to the answer. you feel the need to put others down. fuck you.

**Comment by sholladay** [comment]
@DevelopedByDavid we don't expect you to understand the internals of Ky. Equally, I hope you don't expect us to understand Laravel or where exactly the friction is coming from in the Ky <--> Laravel relationship. I can make some educated guesses and point you to related technical resources but at the end of the day, I know nothing about how they've implemented Ky. Did they follow our instructions? Is their system mangling our import statements? I have no idea. This is why Sindre linked to the release notes, which link to [this useful gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), which explains _what Ky needs_ to be imported. That's about the most help we can provide without seeing your code and having an understanding of the other technologies you are using. 

I, for one, would be more than happy to dig in further and help research and debug the problem. But that requires a lot of time and effort, which won't always be volunteered for free by every maintainer. Personally, I have no plans to learn Laravel at the moment. I'm available for hire if you specifically want a Ky maintainer to look into this. But what I would recommend instead is contacting the Laravel folks who integrated Ky, and ask them if they know what's going on. It could be as simple as enabling a configuration option. If they don't have a solution, then they should reach out to us and we can work together to create one by explaining what we need from each other. That will be vastly more efficient and you can help facilitate those conversations, regardless of your experience level.

**Comment by BoilingSoup** [comment]
For people running into this with nextjs + jest... 
Both nextjs and jest support ESM (although they call it experimental support.) 

The problem is that the official jest wrapper by nextjs exposes a buggy configuration object that doesn't truly overwrite the settings to allow ESM imports in next/jest. You can modify the settings to enable ESM in next/jest by following this https://github.com/vercel/next.js/issues/40183#issuecomment-1249077718

**Comment by nficano** [comment]
> I think you could have easily Googled the error and figured this out yourself.

I love when people say this and then their response becomes the top result for the issue on Google.

**Comment by DevelopedByDavid** [comment]
> 

Agreed

**Comment by mohit-dhote** [comment]
i'm getting the similar error in index.js  

const random = require('random'); // Import the Random library
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Mohit Dhote\hacktoberfest\github-bot\node_modules\random\dist\random.module.js from C:\Users\Mohit Dhote\hacktoberfest\github-bot\index.js not supported.
Instead change the require of random.module.js in C:\Users\Mohit Dhote\hacktoberfest\github-bot\index.js to a dynamic import() which is available in all CommonJS 
modules.
    at Object.<anonymous> (C:\Users\Mohit Dhote\hacktoberfest\github-bot\index.js:4:16) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.9.0
