### ISSUE TITLE
Does ky-universal have the same API methods as ky?

### ISSUE THREAD

**Issue by AniaMakes** [sindresorhus/ky-universal#3]
We are definitely sending a non 2xx response to the ky.post (using ky-universal), and no error is thrown. We assumed that both ky and ky-universal have the same methods, but upon reading the read.me for ky-universal it is not explicitly stated that it does (or doesn't for that matter). 

Would you mind updating the read.me to be more explicit regarding how ky-universal can be used?

Many thanks!

**Comment by sholladay** [comment]
The same methods are supported. This library is a very thin wrapper around Ky and does not have any special behavior of its own. It simply includes polyfills that enable Ky to work more seamlessly in environments like Node.js. That way you can use Ky without setting those up yourself, which is convenient because you may not want to worry about which `fetch()` polyfill library to use, for example. With `ky-universal`, it "just works".

Based on your description, it sounds like you could be having a problem with [`throwHttpErrors`](https://github.com/sindresorhus/ky/tree/0a6beb1327e0c0be51f515b79b9c09f455601b75#throwhttperrors) somehow. But without further details, it's hard for me to know what might be happening. I would have to guess that you are not `await`ing or `catch`ing the response properly.

**Comment by sindresorhus** [comment]
> but upon reading the read.me for ky-universal it is not explicitly stated that it does (or doesn't for that matter).

It *is* stated:

> Use it like you would use Ky:

But we can make it even more explicit.
