### ISSUE TITLE
next js - error: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by oldo** [sindresorhus/ky-universal#30]
I have a very simple fetcher that I'm setting up like so:

```
import ky from 'ky-universal';

const fetchFromApi = ky.extend({
  prefixUrl: process.env.BE_API_ROOT_DOMAIN,
});

export default fetchFromApi;
```

Which is giving the following error:

![Screen Shot 2021-01-15 at 17 17 57](https://user-images.githubusercontent.com/4557648/104688931-c5f5f780-5755-11eb-9c9d-6bed8fdf28fe.jpg)

Can't put my finger on it... Any ideas?

**Comment by sindresorhus** [comment]
I think it would be better to ask this on the Next.js support channels. This package is a valid ESM package.

**Comment by husayt** [comment]
This is not a next related issue. But rather seems that ky-universal has not got commonjs bundle.

to use from node with `require` it need to have a commonjs bundle. Currently it only has esm and browser bundles. Would be great to add commonjs output too.

**Comment by sholladay** [comment]
@husayt that's what we had previously. You can use `ky-universal` v0.8.2 or below if you need CommonJS support. We dropped it because Node 14 and above support ES modules and that's what everything should be going forward. That matters because as of last October, Node 14 is the active LTS version. We waited long enough, it is time for the community to make the transition. Tell the Next.js folks you want ESM support.

**Comment by husayt** [comment]
Thanks for providing wider context to this. This makes sense now.

**Comment by rommyarb** [comment]
Any temporary solution?

**Comment by sholladay** [comment]
@rommyarb yes, I would recommend doing `npm install ky@0.25 ky-universal@0.8`

Those versions support CommonJS and should work fine.
