### ISSUE TITLE
Ky requires DOM types

### ISSUE THREAD

**Issue by obostjancic** [sindresorhus/ky-universal#40]
Hi, 

When using `ky-universal` with Typescript it requires DOM types (`"lib": ["dom"]`) to be included in `tsconfig`, because of it's dependency on `ky`. i. e. without it the build fails with:
```
node_modules/ky/index.d.ts:426:11 - error TS2304: Cannot find name 'Request'.
```
This is a bit inconvenient when using `ky-universal` in a node.js service since it doesn't make sense to add DOM types to a backend project. 

Are there any workarounds for this that you are aware of? 

Thanks!

**Comment by sholladay** [comment]
I'm not aware of any solutions to this. However, since Node is getting native implementations for `Request`, `Response`, `fetch`, etc, I suspect it's going to become increasingly common for backend projects to rely on the DOM types. A bit strange, for sure. Maybe TypeScript will reorganize these things in the future...
