### ISSUE TITLE
TypeError: Headers is not a constructor

### ISSUE THREAD

**Issue by tiagosiebler** [sindresorhus/ky-universal#7]
I've had a somewhat frustrating start to ky, not sure what I'm doing wrong

```
(node:29176) UnhandledPromiseRejectionWarning: TypeError: Headers is not a constructor
    at new Ky (/Volumes/Repositories/Private/apitests/testProj1/node_modules/ky/umd.js:211:20)
    at Function.ky.(anonymous function) [as get] (/Volumes/Repositories/Private/apitests/testProj1/node_modules/ky/umd.js:389:37)
    at getParentChildEndpoint (/Volumes/Repositories/Private/apitests/testProj1/src/api/util/getParentChildEndpoint.js:14:16)
    at Object.getStatus (/Volumes/Repositories/Private/apitests/testProj1/src/api/instanceApi.js:49:22)
```

Rerproduced like this:
```
const ky = require('ky-universal').default;

const prefix = 'http://aa9da6ff.ngrok.io/api/instances/gub6r';
const instanceApi = ky.create({ prefixUrl: prefix, throwHttpErrors: false });
const result = await instanceApi.get('status').json();
```

This seems to be line 211 in umd.js:
![Screenshot 2019-06-17 at 11 15 57](https://user-images.githubusercontent.com/14090872/59597278-50492600-90f1-11e9-9e5c-b8972feb86a2.png)

I have both KY and Ky-universal installed. What am I doing wrong or missing? 

If I try to catch this, the error is the same as that shown in the stack trace. I'd expect a HTTP error (like 404), not a stack trace like this. Thanks!

**Comment by sindresorhus** [comment]
@szmarczak Or we can just check each global individually?

**Comment by szmarczak** [comment]
Yep. That would work. Optionally we could add a `global` option where we would provide all the necessary objects, example:

```js
ky('', {
    global: {
        fetch,
        AbortController,
        ...
    }
});
```

**Comment by sphinxc0re** [comment]
This still doesn't seem to work for me. `globalThis.Headers` seems to be undefined in Node but not in the browser

**Comment by sholladay** [comment]
Hi @sphinxc0re, we'll need more details about your environment.

**Comment by sphinxc0re** [comment]
Sure, sorry. I'm working with SvelteKit and vite in development. This means that the application is loaded as pure ESM in develop and not bundled. I'm using SSR so every component is rendered in node and the browser. And all of that is running inside docker 😅

**Comment by sholladay** [comment]
@sphinxc0re is there any chance the Node version you're specifying isn't actually being honored? The reason I ask is that `globalThis` was introduced in Node 12. Many PaaS systems, Docker images, and `nvm` installations in the wild haven't been updated to support Node 14 yet. And I know at least with nvm, if you ask it to `nvm use` a version that hasn't been `nvm install`'d, it will effectively ignore that command.

**Comment by sphinxc0re** [comment]
I'm using the official `node:14` docker image. https://hub.docker.com/_/node. Let me check if it's actually node 14

**Comment by sphinxc0re** [comment]
I think I found the culprit. Only the `browser.js` is loaded. I don't know why that is. Probably a vite thing.

**Comment by sholladay** [comment]
Sounds like it is giving preference to the `browser` field in package.json, which we define here: https://github.com/sindresorhus/ky-universal/blob/ca24367ea3b5d5d4d3965396a9aeca7265011b9c/package.json#L82

I believe many tools do this, [including webpack](https://github.com/webpack/webpack/issues/4674). My understanding is that `browser` is a very old convention that predates the common usage of isomorphic JavaScript and so it wasn't just used as an _alternative_ export, but rather as a _replacement_, to signify that a library is only meant for the browser.

npm says in their [documentation](https://docs.npmjs.com/cli/v7/configuring-npm/package-json):
> If your module is meant to be used client-side the browser field should be used instead of the main field. This is helpful to hint users that it might rely on primitives that aren't available in Node.js modules. (e.g. window)

Key phrase there being "instead of".

Contrast that to the much newer `exports` field, where we can define various alternative exports, which is how all of this stuff should have worked from the beginning.

Another thing to consider is that tooling that hasn't been updated to support `exports` may not expect `browser` to be in ESM format.

I wonder if we should just remove the `browser` field from ky-universal. For old tooling that doesn't yet support `exports`, maybe we could re-introduce `"main": "index.js"` as that will likely have the broadest compatibility.

**Comment by sphinxc0re** [comment]
I was able to tell Vite that "node" was a valid export and now... (I have different problems)

**Comment by markwoon** [comment]
If it helps, I've a simple test case for this @ https://github.com/markwoon/ky-universal-jest

Just run:
```
# yarn build
# node dist/main.bundle.js
```
